## Copyright 2020 Green River IT as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/KubeHostNet/  

# Kubernetes initialization steps for Master.  Assumes that the generic installation has already been completed.    
- name: Initialize Kubernetes on a Master node 
  hosts: k8smaster
  remote_user: kubernetes-host
  become: true
  become_method: sudo
  become_user: root

  tasks:  

     - name: Run kubeadm init using the calico variable just created
       shell: sudo kubeadm init --kubernetes-version=1.13.1 --pod-network-cidr=192.168.0.0/16 | tee kubeadm-init.out
       become: yes
       become_user: root  

     #Confirm that kubeadm init has created the admin.conf file.  This will be necessary before subsequent tasks can be started.  
     - name: Wait until the file /etc/kubernetes/admin.conf is present before continuing
       wait_for:
         path: /etc/kubernetes/admin.conf
       #sudo: true
       #sudo_user: kubernetes-host

     - name: Create kube directory 
       shell: mkdir -p /home/kubernetes-host/.kube
       become: yes
       become_user: root  
       #sudo: true
       #sudo_user: kubernetes-host

     - name: Change ownership of /home/kubernetes-host/.kube
       shell: chown -R kubernetes-host:kubernetes-host /home/kubernetes-host/.kube
       become: yes
       become_user: root

     - name: Change ownership of /etc/kubernetes so that the next step can copy a config file from it 
       shell: chown -R kubernetes-host:kubernetes-host /etc/kubernetes
       become: yes
       become_user: root

     - name: copy admin_conf file into kube_config directory 
       shell: cp -i /etc/kubernetes/admin.conf /home/kubernetes-host/.kube/config
       #sudo: true
       #sudo_user: kubernetes-host

     - name: Change ownership of kube_config file 
       shell: chown kubernetes-host:kubernetes-host /home/kubernetes-host/.kube/config 
       become: yes
       become_user: root
       #shell: chown $(id -u):$(id -g) $HOME/.kube/config 
       #sudo: true
       #sudo_user: kubernetes-host
