## Copyright 2020 Green River IT as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/KubeHostNet/  

# Configure networking for the cluster on Master.  This must be preceded by Kubernetes initialization steps for Master in a different playbook.  Also assumes that the generic installation has already been completed.    
- name: Apply networking for Kubernetes cluster on a Master node 
  hosts: k8smaster
  remote_user: kubernetes-host
  become: true
  become_method: sudo
  become_user: root

  tasks:  

     - name: Apply the RBAC config file to the cluster
       shell: kubectl apply -f /home/kubernetes-host/pod-network-yaml/rbac-kdd.yaml | tee kubeadm-rbac-kdd.out

     - name: Deploy a pod network to the cluster 
       shell: kubectl apply -f /home/kubernetes-host/pod-network-yaml/calico.yaml | tee kubeadm-calico.out
