## Copyright 2020 Green River IT as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/KubeHostNet/  
  
---
# Kubernetes installation steps that apply to all types of nodes.  Will be followed by specific additional steps for each type of node.  
- name: Remove k8s generic all types of nodes.
  hosts: k8smaster, k8sworker
  remote_user: kubernetes-host
  become: true
  become_method: sudo
  become_user: root

  tasks:

     - name: disable service kubelet and ensure it is not masked before running kubeadm after
       systemd:
         name: kubelet
         enabled: no
       become: yes
       become_method: sudo
       become_user: root

     - name: Make sure docker service is NOT running
       systemd:
         state: inactive
         name: docker.service

     - name: disable service docker and ensure it is not masked
       systemd:
         name: docker.service
         enabled: no

     - name: remove any previous versions of docker
       yum:
         name: docker, docker-client, docker-client-latest, docker-common, docker-latest, docker-latest-logrotate, docker-logrotate, docker-engine
         state: absent
         lock_timeout: 180

     # Note: version numbers of kubectl must match the --kubernetes-version argument of the kubeadm init command in other files in this group.
     - name: remove kubelet kubeadm and kubectl
       yum:
         name: kubelet-1.13.1, kubeadm-1.13.1, kubectl-1.13.1, kubernetes-cni-0.6.0
         state: absent

     - name: Perform yum update of all packages
       yum:
         name: '*'
         state: latest
         lock_timeout: 180
